name: Build, Test, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Prevent multiple concurrent workflow runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Changed: Only needs read access now
      id-token: write # Optional: If using OIDC for authentication instead of token

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # No fetch-depth needed anymore as we don't modify history

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        # TODO: Add caching for Playwright browsers

      - name: Format code # Check formatting on PRs and main
        run: pnpm format

      - name: Run Lint # Lint on PRs and main
        run: pnpm lint

      - name: Run Tests # Test on PRs and main
        run: pnpm test

      # --- Publish Steps (only run on push to main branch) ---

      # REMOVED: Configure Git step
      # REMOVED: Bump version step

      - name: Build project
        # Build runs after tests pass on the main branch commit (post-merge)
        run: pnpm build

      - name: Setup Node.js for publish
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Publish to NPM
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # REMOVED: Push changes to GitHub step
